### ISSUE TITLE
Extending to More Classes?

### ISSUE THREAD

**Issue by aflah02** [THU-KEG/Skill-Neuron#1]
Hey!
Thanks for the great work and the code
I saw you currently support only some set of labels, I want to try some experiments with more classes is it possible to modify the code to achieve that? Would just changing the binarizing part suffice or would I need to change the modelling parts too?

**Comment by WhenWen** [comment]
Hi! We would recommend you binarize the dataset in a similar fashion as in _src/binarize.py_ and then perform the binary probing. You may also refer to our paper for how we process similar tasks like MNLI.

**Comment by aflah02** [comment]
Thanks!
